# Tennis pre-match prediction

## Test with a first dataset generate by a postegresql database and 3 tennis statistiques sources

In [10]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import pandas as pd
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
#%matplotlib inline
#import matplotlib
#import matplotlib.pyplot as plt
#plt.rcParams['axes.labelsize'] = 14
#plt.rcParams['xtick.labelsize'] = 12
#plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

### get data

##### CSV version

In [11]:
PATH = "dataset"
NAME = "dataset_train_final.csv"
PRED = "dataset_pred_final.csv"

def load_dataset_csv(path=PATH, name=NAME):
    csv_path = os.path.join(path,  name)
    return pd.read_csv(csv_path)

def load_predictset_csv(path=PATH, name=PRED):
    csv_path = os.path.join(path, name)
    return pd.read_csv(csv_path)

##### SQL version

In [12]:
from sqlalchemy import create_engine
import psycopg2 as pg
import requests as req

URL = 'postgresql://dataset:dataset1747@35.204.62.91:5432/dataset-dump1'
engine = create_engine(URL)

def load_dataset_sql():
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/extract_dataset.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text, conn)

def load_predictset_sql():
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/extract_predset.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text, conn)


In [13]:
dataset = load_dataset_sql()
dataset.head()

id                            url_match_flash  \
0  31497  https://www.flashscore.com/match/A5WZiVlj   
1   8812  https://www.flashscore.com/match/IcCrEkbs   
2  53036  https://www.flashscore.com/match/GlOoStQG   
3  12508  https://www.flashscore.com/match/xtx8SEe6   
4  47243  https://www.flashscore.com/match/Gt8mGhDk   

                                    url_match_atp  \
0     /en/scores/archive/madrid/1536/2002/results   
1   /en/scores/archive/bucharest/773/2012/results   
2    /en/scores/archive/valencia/573/2003/results   
3  /en/scores/archive/cincinnati/422/2003/results   
4   /en/scores/archive/stuttgart/321/2005/results   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...          Madrid   
1  https://www.flashscore.com/tennis/atp-singles/...       Bucharest   
2  https://www.flashscore.com/tennis/atp-singles/...        Valencia   
3  https://www.flashscore.com/tennis/atp-singles/...      Cincinnati   
4  https://www.flashscore.com/tennis/atp-singles/...       Stuttgart   

                   name_tour_atp name_tour_csv    round_flash round_csv  \
0      ATP Masters Series Madrid        Madrid  Semi-finals\n        SF   
1                      Bucharest     Bucharest  1/16-finals\n       R32   
2                       Valencia      Valencia  1/16-finals\n       R32   
3  ATP Masters Series Cincinnati    Cincinnati  1/32-finals\n       R64   
4                      Stuttgart     Stuttgart   1/8-finals\n       R16   

   qualif         ...          return_rating_20years  \
0   False         ...                     -14.370963   
1   False         ...                      23.070261   
2   False         ...                      -2.654034   
3   False         ...                     -17.435662   
4   False         ...                     -59.924116   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                            -3.861322             -0.921584   
1                             1.648693              4.137255   
2                            -3.187368              3.777288   
3                            -1.833359             -5.655868   
4                           -12.098007            -12.726353   

  return_games_played_20years  service_point_won_20years  \
0                   -0.439661                  -3.069863   
1                   -0.348039                  -6.426471   
2                    2.050648                   6.983664   
3                    0.719789                  -1.955712   
4                    1.500216                  -0.895951   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                -3.633980               -2.877679                    2.0   
1                 5.169935               -0.624183                    0.0   
2                -1.720767                2.407857                    1.0   
3                -2.947333               -2.154163                    1.0   
4               -12.855204               -6.047258                    0.0   

   h2h minutes_loser_winner  
0  0.0            -0.276389  
1  1.0            -0.074712  
2  0.0            -0.833793  
3  0.0             0.866020  
4  1.0             0.826643  

[5 rows x 91 columns]

In [14]:
predset = load_predictset_sql()
predset.head()

id                            url_match_flash  \
0  21740  https://www.flashscore.com/match/b5g7mYRl   
1  20836  https://www.flashscore.com/match/zVGlPvs3   
2  20837  https://www.flashscore.com/match/j3IgqvIj   
3  20838  https://www.flashscore.com/match/SSTreMbC   
4  20839  https://www.flashscore.com/match/hAsqo4ES   

                                url_match_atp  \
0   /en/scores/archive/halle/500/2017/results   
1  /en/scores/archive/geneva/322/2018/results   
2  /en/scores/archive/geneva/322/2018/results   
3  /en/scores/archive/geneva/322/2018/results   
4  /en/scores/archive/geneva/322/2018/results   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...           Halle   
1  https://www.flashscore.com/tennis/atp-singles/...          Geneva   
2  https://www.flashscore.com/tennis/atp-singles/...          Geneva   
3  https://www.flashscore.com/tennis/atp-singles/...          Geneva   
4  https://www.flashscore.com/tennis/atp-singles/...          Geneva   

                     name_tour_atp name_tour_csv       round_flash round_csv  \
0                            Halle         Halle      1/8-finals\n       R16   
1  Banque Eric Sturdza Geneva Open        Geneva           Final\n         F   
2  Banque Eric Sturdza Geneva Open        Geneva     Semi-finals\n        SF   
3  Banque Eric Sturdza Geneva Open        Geneva     Semi-finals\n        SF   
4  Banque Eric Sturdza Geneva Open        Geneva  Quarter-finals\n        QF   

   qualif         ...          return_rating_20years  \
0   False         ...                      24.842458   
1   False         ...                       0.493590   
2   False         ...                      -8.546491   
3   False         ...                       9.428644   
4   False         ...                       1.731312   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                             4.115788              3.518021   
1                            -2.628205              5.057692   
2                            -1.388158              1.012281   
3                             1.402381              1.028337   
4                            -1.689350              3.800157   

  return_games_played_20years  service_point_won_20years  \
0                   -0.672582                   0.603285   
1                    0.378205                   4.775641   
2                    1.748246                   4.722807   
3                   -0.094823                  -4.616919   
4                    0.816122                   7.571281   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                 5.072365                2.703841                    1.0   
1                -1.115385                1.679487                    2.0   
2                -2.367982                1.038158                    0.0   
3                 2.111454               -1.201479                    1.0   
4                -0.217313                3.489839                    2.0   

        h2h minutes_loser_winner  
0  0.000000             0.106283  
1 -0.333333             0.179946  
2  1.000000            -0.047688  
3  0.000000            -0.111542  
4 -0.333333                  NaN  

[5 rows x 91 columns]

In [15]:
predset.shape

(3761, 91)

In [16]:
dataset.shape

(34148, 91)

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34148 entries, 0 to 34147
Data columns (total 91 columns):
id                                      34148 non-null int64
url_match_flash                         34148 non-null object
url_match_atp                           34148 non-null object
url_tour                                34148 non-null object
name_tour_flash                         34148 non-null object
name_tour_atp                           34148 non-null object
name_tour_csv                           34148 non-null object
round_flash                             34148 non-null object
round_csv                               34148 non-null object
qualif                                  34148 non-null bool
door                                    34148 non-null object
surface                                 34148 non-null object
prize                                   34148 non-null int64
year_atp                                34148 non-null object
year_flash                 

In [18]:
# to make this notebook's output identical at every run
np.random.seed(42)

### split the training set and the test set into 2 batchs with the hash id

In [19]:
import hashlib

def test_set_check(identifier, test_ratio, hash=hashlib.md5):
    return bytearray(hash(np.int64(identifier)).digest())[-1] < 256 * test_ratio

def split_train_test_by_id(data, test_ratio, id_column):
    ids = data[id_column]
    in_test_set = ids.apply(lambda id_: test_set_check(id_, test_ratio))
    return data.loc[~in_test_set], data.loc[in_test_set]

In [20]:
train_set, test_set = split_train_test_by_id(dataset, 0.2, "id")

In [21]:
print(train_set.shape)
train_set.head()

(27148, 91)


id                            url_match_flash  \
0  31497  https://www.flashscore.com/match/A5WZiVlj   
1   8812  https://www.flashscore.com/match/IcCrEkbs   
2  53036  https://www.flashscore.com/match/GlOoStQG   
3  12508  https://www.flashscore.com/match/xtx8SEe6   
4  47243  https://www.flashscore.com/match/Gt8mGhDk   

                                    url_match_atp  \
0     /en/scores/archive/madrid/1536/2002/results   
1   /en/scores/archive/bucharest/773/2012/results   
2    /en/scores/archive/valencia/573/2003/results   
3  /en/scores/archive/cincinnati/422/2003/results   
4   /en/scores/archive/stuttgart/321/2005/results   

                                            url_tour name_tour_flash  \
0  https://www.flashscore.com/tennis/atp-singles/...          Madrid   
1  https://www.flashscore.com/tennis/atp-singles/...       Bucharest   
2  https://www.flashscore.com/tennis/atp-singles/...        Valencia   
3  https://www.flashscore.com/tennis/atp-singles/...      Cincinnati   
4  https://www.flashscore.com/tennis/atp-singles/...       Stuttgart   

                   name_tour_atp name_tour_csv    round_flash round_csv  \
0      ATP Masters Series Madrid        Madrid  Semi-finals\n        SF   
1                      Bucharest     Bucharest  1/16-finals\n       R32   
2                       Valencia      Valencia  1/16-finals\n       R32   
3  ATP Masters Series Cincinnati    Cincinnati  1/32-finals\n       R64   
4                      Stuttgart     Stuttgart   1/8-finals\n       R16   

   qualif         ...          return_rating_20years  \
0   False         ...                     -14.370963   
1   False         ...                      23.070261   
2   False         ...                      -2.654034   
3   False         ...                     -17.435662   
4   False         ...                     -59.924116   

  first_serve_return_point_won_20years  bp_converted_20years  \
0                            -3.861322             -0.921584   
1                             1.648693              4.137255   
2                            -3.187368              3.777288   
3                            -1.833359             -5.655868   
4                           -12.098007            -12.726353   

  return_games_played_20years  service_point_won_20years  \
0                   -0.439661                  -3.069863   
1                   -0.348039                  -6.426471   
2                    2.050648                   6.983664   
3                    0.719789                  -1.955712   
4                    1.500216                  -0.895951   

  return_point_won_20years total_point_won_20years winner_loser_match_win  \
0                -3.633980               -2.877679                    2.0   
1                 5.169935               -0.624183                    0.0   
2                -1.720767                2.407857                    1.0   
3                -2.947333               -2.154163                    1.0   
4               -12.855204               -6.047258                    0.0   

   h2h minutes_loser_winner  
0  0.0            -0.276389  
1  1.0            -0.074712  
2  0.0            -0.833793  
3  0.0             0.866020  
4  1.0             0.826643  

[5 rows x 91 columns]

In [22]:
print(test_set.shape)
test_set.head()

(7000, 91)


id                            url_match_flash  \
8   16168  https://www.flashscore.com/match/SCeQru63   
14  58303  https://www.flashscore.com/match/jB1JtM64   
16   6713  https://www.flashscore.com/match/SfK5pURK   
20   4251  https://www.flashscore.com/match/AeRkQsug   
23  15056  https://www.flashscore.com/match/vg2Z57xB   

                                        url_match_atp  \
8            /en/scores/archive/doha/451/2008/results   
14        /en/scores/archive/zagreb/2276/2011/results   
16         /en/scores/archive/bastad/316/2013/results   
20  /en/scores/archive/australian-open/580/2001/re...   
23   /en/scores/archive/delray-beach/499/2015/results   

                                             url_tour  name_tour_flash  \
8   https://www.flashscore.com/tennis/atp-singles/...             Doha   
14  https://www.flashscore.com/tennis/atp-singles/...           Zagreb   
16  https://www.flashscore.com/tennis/atp-singles/...           Bastad   
20  https://www.flashscore.com/tennis/atp-singles/...  Australian Open   
23  https://www.flashscore.com/tennis/atp-singles/...     Delray Beach   

      name_tour_atp    name_tour_csv       round_flash round_csv  qualif  \
8              Doha             Doha     Semi-finals\n        SF   False   
14           Zagreb           Zagreb     1/16-finals\n       R32   False   
16           Bastad           Bastad     1/16-finals\n       R32   False   
20  Australian Open  Australian Open     1/32-finals\n       R64   False   
23     Delray Beach     Delray Beach  Quarter-finals\n        QF   False   

           ...          return_rating_20years  \
8          ...                     -17.518324   
14         ...                     -14.760084   
16         ...                      40.425170   
20         ...                     -17.300000   
23         ...                       8.973000   

   first_serve_return_point_won_20years  bp_converted_20years  \
8                             -3.023477             -3.507222   
14                            -1.646162             -4.271457   
16                             7.717347              6.785374   
20                            -1.475000             -7.091667   
23                             2.178111             -1.823889   

   return_games_played_20years  service_point_won_20years  \
8                    -0.570255                  -2.045622   
14                    0.837199                   9.323894   
16                   -1.143197                  -2.169388   
20                    0.483333                  -1.505556   
23                   -1.868222                  -6.641889   

   return_point_won_20years total_point_won_20years winner_loser_match_win  \
8                 -3.413699               -2.469572                    3.0   
14                -2.789496                2.928291                    2.0   
16                 8.471769                2.895238                    0.0   
20                -2.863889               -2.025000                    0.0   
23                 3.478333               -2.047778                    0.0   

         h2h minutes_loser_winner  
8   0.250000             0.316686  
14 -0.333333            -0.503471  
16  1.000000                  NaN  
20  1.000000             0.149377  
23  1.000000             0.338504  

[5 rows x 91 columns]

In [23]:
dataset = train_set.copy()

In [24]:
dataset["draw_size"] = dataset["draw_size"].apply(lambda x: str(x))
dataset["draw_size"] = dataset["draw_size"].astype("object")
index_draw_size = list(dataset["draw_size"].value_counts().index)
dataset["draw_size"].value_counts()

32     9754
128    4758
28     3155
56     3120
48     2549
96     1990
64     1737
8        74
16       11
Name: draw_size, dtype: int64

In [25]:
index_level_tour = list(dataset["level_tour"].value_counts().index)
dataset["level_tour"].value_counts()

A    16240
M     6233
G     4590
F       85
Name: level_tour, dtype: int64

In [26]:
index_surface = list(dataset["surface"].value_counts().index)
dataset["surface"].value_counts()

Hard      15239
Clay       8119
Grass      3231
Carpet      559
Name: surface, dtype: int64

In [27]:
index_door = list(dataset["door"].value_counts().index)
dataset["door"].value_counts()

Outdoor    22498
Indoor      4650
Name: door, dtype: int64

In [28]:
index_round_csv = list(dataset["round_csv"].value_counts().index)
dataset["round_csv"].value_counts()

R32     9529
R16     5100
R64     4937
R128    3039
QF      2552
SF      1293
F        627
RR        71
Name: round_csv, dtype: int64

In [29]:
dataset["year_atp"].value_counts()

2016    1906
2009    1826
2014    1798
2010    1792
2006    1785
2011    1774
2005    1764
2013    1745
2012    1727
2004    1727
2008    1719
2007    1705
2003    1658
2001    1590
2002    1572
2015    1060
Name: year_atp, dtype: int64

### add column result that will be the y axis on the dataset for the prediction

In [30]:
dataset.shape

(27148, 91)

In [31]:
dataset.insert(dataset.shape[1], "result", np.random.randint(2, size=dataset.shape[0]))

In [32]:
dataset["result"].value_counts()

1    13585
0    13563
Name: result, dtype: int64

In [33]:
test_set.insert(test_set.shape[1], "result", np.random.randint(2, size=test_set.shape[0]))

In [34]:
test_set["result"].value_counts()

1    3535
0    3465
Name: result, dtype: int64

### transformer

In [35]:
from sklearn.base import BaseEstimator, TransformerMixin

# A class to select numerical or categorical columns 
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [36]:
class reverseStats(BaseEstimator, TransformerMixin):
       
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        ## while on each row : if result = 1 nothing else opponent each value in each collumn
        def wh(a):
            if (a["result"] == 0):
                a = a.apply(lambda x: x * -1)
            return a
        
        X = X.fillna(0)
        X = X.apply(wh, axis=1)
        X = X.drop("result", axis=1)
        return X

In [37]:
stats_col = ["serve_rating_1year", "aces_1year", "double_faults_1year", "first_serve_1year", "first_serve_point_won_1year",
       "second_serve_point_won_1year", "bp_saved_1year", "service_game_played_1year", "return_rating_1year",
       "first_serve_return_point_won_1year", "bp_converted_1year", "return_games_played_1year", "service_point_won_1year",
       "return_point_won_1year", "total_point_won_1year", "serve_rating_20years",
       "aces_20years", "double_faults_20years", "first_serve_20years", "first_serve_point_won_20years", "second_serve_point_won_20years",
       "bp_saved_20years", "service_game_played_20years", "return_rating_20years", "first_serve_return_point_won_20years",
       "bp_converted_20years", "return_games_played_20years", "service_point_won_20years", "return_point_won_20years",
       "total_point_won_20years", "h2h", "minutes_loser_winner", "result"]
len(stats_col)

33

In [38]:
from sklearn.pipeline import Pipeline

stats_pipeline = Pipeline([
        ("select_stats", DataFrameSelector(stats_col)),
        ("reverse", reverseStats()),
    ])

stats_pipeline.fit_transform(dataset).shape

(27148, 32)

In [39]:
stats_pipeline.fit_transform(dataset)

serve_rating_1year  aces_1year  double_faults_1year  first_serve_1year  \
0               12.619211    0.216533             0.910997           5.292173   
1              -29.350694   -8.222222            -0.055556           0.576389   
2              -28.925223   -4.390253             2.524330           0.473437   
3                2.760000   -1.307415             0.039048           1.938231   
4                3.183059   -6.966392            -2.358852           8.609417   
5               15.372953   -0.937427             0.627339           4.621053   
6               70.226190    7.142857            -1.130952           5.142857   
7                0.458225   -0.296050             0.237635          -3.945671   
9               48.040292    0.343161            -2.199782           8.098888   
10              -8.989354   -1.820860            -0.403192          -0.158523   
11             -18.981481    5.064815             0.981481          -3.296296   
12               2.441959    1.319542             0.510502          -3.506213   
13              14.869333   -0.162000            -0.278654           3.465990   
15              31.468699    2.511382            -0.985772          -0.857317   
17               0.000000    0.000000             0.000000           0.000000   
18              28.257576   -0.844697            -0.625000          13.590909   
19              -5.795406    0.838457             0.860133          -4.852057   
21              -0.500000   -5.000000            -0.500000           9.500000   
22             -15.852728   -0.426935             4.390675          -3.551687   
24              66.500000    3.833333            -0.000000         -13.666667   
26              17.944306    5.840335             1.169259          -2.093656   
27               7.166667    0.273810            -0.059524          -0.936508   
28             -11.643411   -0.515504             0.957364           0.290698   
29              17.962963   -0.169753             0.922840           7.986111   
30              -5.536765   -1.281863             1.568627           0.377451   
31             -20.482456   -1.642544             2.081140          -1.495614   
32               1.942308   -3.147436            -0.262821          -3.839744   
33             -17.757687   -3.441624             0.347050          -0.428061   
34             -59.000000   -6.941176             0.029412          -1.264706   
35              66.250000    3.250000            -7.250000           5.750000   
...                   ...         ...                  ...                ...   
34112           -7.462852    1.151320             1.159571          -5.349812   
34113          -18.884259   -1.004630            -0.370370          -7.875000   
34115            4.309028    4.645833             1.618056          -9.625000   
34117           42.252315   13.537963             1.411111          -4.918056   
34118           -8.613725   -2.684314            -1.587255           6.005882   
34119           10.736413    0.976449            -0.723732           6.606884   
34120          -14.288652    0.996809             1.135461          -6.252482   
34121           -4.340799   -1.357627            -0.844391          -4.337692   
34123           -1.764012    0.877444            -0.346587          -1.616660   
34124           32.897287    4.516085             0.040089           5.895127   
34125          -34.578122   -2.685295             0.957098          -4.959708   
34128          -19.490643   -1.328363             0.362865           1.978947   
34129            8.917708    1.684375             0.636458           0.900000   
34130           29.523770    5.727643            -1.334153          -3.622619   
34132          -50.361467   -3.711884             1.074439          -7.782799   
34133          -30.720313    0.836682             0.654500          -9.836392   
34134            6.531916   -0.646567            -0.893204           6.869370   
34135          -42.683931   -8.242945 

In [40]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
from sklearn.preprocessing import label_binarize

In [41]:
class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, classes):
        self.classes = classes
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = label_binarize(X, classes=self.classes)
        return enc

In [42]:
round_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["round_csv"])),
        ("cat_encoder", CustomLabelBinarizer(index_round_csv)),
    ])

round_pipeline.fit_transform(dataset)

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [43]:
round_pipeline.fit_transform(dataset).shape

(27148, 8)

In [44]:
surface_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["surface"])),
        ("cat_encoder", CustomLabelBinarizer(index_surface)),
    ])

surface_pipeline.fit_transform(dataset)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [45]:
surface_pipeline.fit_transform(dataset).shape

(27148, 4)

In [46]:
drawSize_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["draw_size"])),
        ("cat_encoder", CustomLabelBinarizer(index_draw_size)),
    ])

drawSize_pipeline.fit_transform(dataset)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [47]:
drawSize_pipeline.fit_transform(dataset).shape

(27148, 9)

In [48]:
levelTour_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["level_tour"])),
        ("cat_encoder", CustomLabelBinarizer(index_level_tour)),
    ])

levelTour_pipeline.fit_transform(dataset)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [49]:
levelTour_pipeline.fit_transform(dataset).shape

(27148, 4)

In [50]:
from sklearn.preprocessing import Imputer

weather_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["temp_weather", "press_weather", "humid_weather"])),
        ('imputer', Imputer(strategy="mean")),
    ])

weather_pipeline.fit_transform(dataset)

/Users/pleroux/.local/share/virtualenvs/tennis-backend-Bg5PmMLW/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 45.        ,  27.49      ,  93.        ],
       [ 59.        ,  29.46      , 100.        ],
       [ 64.        ,  29.9       ,  77.        ],
       ...,
       [ 61.        ,  29.77      ,  67.        ],
       [ 71.        ,  29.60130104,  62.        ],
       [ 54.        ,  22.26      ,  82.        ]])

In [51]:
weather_pipeline.fit_transform(dataset).shape

(27148, 3)

In [52]:
from sklearn.preprocessing import Imputer

year_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["year_atp"])),
        ('imputer', Imputer(strategy="most_frequent")),
    ])

year_pipeline.fit_transform(dataset)

/Users/pleroux/.local/share/virtualenvs/tennis-backend-Bg5PmMLW/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[2002.],
       [2012.],
       [2003.],
       ...,
       [2013.],
       [2014.],
       [2014.]])

In [53]:

year_pipeline.fit_transform(dataset).shape

(27148, 1)

In [54]:
class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, sparse_output=False):
        self.sparse_output = sparse_output
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = LabelBinarizer(sparse_output=self.sparse_output)
        return enc.fit_transform(X)

In [55]:
door_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["door"])),
        ("cat_encoder", CustomLabelBinarizer()),
    ])

door_pipeline.fit_transform(dataset)

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [56]:
door_pipeline.fit_transform(dataset).shape

(27148, 1)

In [57]:
class fillna(BaseEstimator, TransformerMixin):
    def __init__(self, val):
        self.val = val
        
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):        
        return X.fillna(self.val)

In [58]:
uncertainty_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["uncertainty_1year", "uncertainty_20years"])),
        ("cat_encoder", fillna(10)),
    ])

uncertainty_pipeline.fit_transform(dataset).shape

(27148, 2)

In [59]:
count_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["count_match_1year", "count_match_20years"])),
        ("cat_encoder", fillna(0)),
    ])

count_pipeline.fit_transform(dataset).shape

(27148, 2)

In [60]:
from sklearn.pipeline import FeatureUnion
preprocess_pipeline = FeatureUnion(transformer_list=[
        ("stats_pipeline", stats_pipeline),
        ("round_pipeline", round_pipeline),
        ("surface_pipeline", surface_pipeline),
        ("drawSize_pipeline", drawSize_pipeline),
        ("levelTour_pipeline", levelTour_pipeline),
        ("weather_pipeline", levelTour_pipeline),
        ("year_pipeline", levelTour_pipeline),
        ("door_pipeline", levelTour_pipeline),
        ("uncertainty_pipeline", levelTour_pipeline),
        ("count_pipeline", count_pipeline),
    ])

In [61]:
X_train = preprocess_pipeline.fit_transform(dataset)

In [62]:
X_train.shape

(27148, 75)

In [63]:
pd.DataFrame(X_train).head()

0         1         2         3         4         5         6   \
0  12.619211  0.216533  0.910997  5.292173  1.937366  2.542619  3.370908   
1 -29.350694 -8.222222 -0.055556  0.576389 -9.423611  3.170139 -3.253472   
2 -28.925223 -4.390253  2.524330  0.473437 -8.280506 -3.186012 -7.716369   
3   2.760000 -1.307415  0.039048  1.938231  1.163401  2.767347 -1.696871   
4   3.183059 -6.966392 -2.358852  8.609417 -3.659661  8.769414 -7.880327   

         7          8          9   ...     65   66   67   68   69   70   71  \
0 -0.091845  15.568988   4.435193  ...    0.0  1.0  0.0  0.0  0.0  1.0  0.0   
1 -0.489583  21.857639   1.722222  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   
2 -1.606324   5.387798   6.242336  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   
3 -0.855238  24.072517   2.518912  ...    0.0  1.0  0.0  0.0  0.0  1.0  0.0   
4 -1.177961  60.143971  10.854823  ...    1.0  0.0  0.0  0.0  1.0  0.0  0.0   

    72     73     74  
0  0.0  187.0  232.0  
1  0.0   72.0   85.0  
2  0.0   75.0  152.0  
3  0.0   45.0   88.0  
4  0.0   33.0   55.0  

[5 rows x 75 columns]

In [64]:
pd.DataFrame(X_train).isnull().any().value_counts()

False    75
dtype: int64

In [65]:
y_train = dataset["result"]
y_train.shape

(27148,)

#### predset preprocess

In [66]:
testset = test_set.copy()

In [67]:
X_test = preprocess_pipeline.fit_transform(testset)
y_test = testset["result"]

### KNN

In [68]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

param_grid = [{'weights': ["uniform", "distance"], 'n_neighbors': [3, 4, 5]}]

knn_clf = KNeighborsClassifier()
grid_search = GridSearchCV(knn_clf, param_grid, cv=5, verbose=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   55.0s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid=[{'weights': ['uniform', 'distance'], 'n_neighbors': [3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [69]:
grid_search.best_params_

{'n_neighbors': 5, 'weights': 'distance'}

In [70]:
grid_search.best_score_

0.668078679829085

In [71]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_jobs=-1, weights='uniform', n_neighbors=3)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=3, p=2,
           weights='uniform')

In [72]:
y_knn_pred = knn_clf.predict(X_train)

from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_knn_pred)

0.8200604096066009

### RF

In [73]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

forest_clf = RandomForestClassifier(random_state=42)
forest_clf.fit(X_train, y_train)
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10, n_jobs=-1)
forest_scores.mean()

/Users/pleroux/.local/share/virtualenvs/tennis-backend-Bg5PmMLW/lib/python3.7/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.8389192665727163

In [74]:
forest_clf_pred = forest_clf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, forest_clf_pred)

0.8381428571428572

### saved the model on the disk

In [75]:
import pickle

PATH = 'models/'

def save_model(obj, name, path=PATH):
    file = open(path + name, 'wb')
    pickle.dump(obj, file)
    file.close()

save_model(forest_clf, "forest_clf")

### GridSearch

In [76]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=100, high=500),
        'max_features': randint(low=5, high=15),
    }

forest_reg = RandomForestClassifier(random_state=42)
rnd_search = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=42, n_jobs=-1)
rnd_search.fit(X_train, y_train) 

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
          fit_params=None, iid='warn', n_iter=10, n_jobs=-1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x122c7d5c0>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x12260ff28>},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring='neg_mean_squared_error',
          verbose=0)

In [77]:
rnd_search.best_params_

{'max_features': 14, 'n_estimators': 314}

In [78]:
feature_importances = rnd_search.best_estimator_.feature_importances_
#sorted(zip(feature_importan)ces, list(dataset.columns.values)), reverse=True))
feature_importances[32:] ## useless

array([1.77953842e-03, 1.59713779e-03, 1.29400854e-03, 9.07995123e-04,
       1.32166321e-03, 1.23334463e-03, 9.89843435e-04, 7.76490713e-05,
       1.62099032e-03, 1.69373621e-03, 1.22516174e-03, 5.13609628e-04,
       1.50651218e-03, 7.07389588e-04, 1.17476465e-03, 1.24828791e-03,
       1.32694234e-03, 9.01097649e-04, 1.00598837e-03, 5.05809474e-05,
       6.22847161e-05, 8.38284674e-04, 8.28803383e-04, 7.12704204e-04,
       7.86824777e-05, 8.18380024e-04, 8.11385293e-04, 6.67458501e-04,
       8.19554511e-05, 8.06513016e-04, 7.66442569e-04, 6.84228257e-04,
       7.41008719e-05, 8.91379656e-04, 8.04493730e-04, 6.97550156e-04,
       6.31106854e-05, 8.48612316e-04, 8.01479117e-04, 6.79138612e-04,
       7.69122368e-05, 3.14189312e-02, 3.75834138e-02])

In [79]:
from sklearn.metrics import accuracy_score

rnd_pred = rnd_search.predict(X_train)

accuracy_score(y_train, rnd_pred)

1.0

In [80]:
save_model(rnd_search, "rnd_search")

### predset

match beetween years 2017 and 2018

In [81]:
valset = predset.copy()

valset.insert(valset.shape[1], "result", np.random.randint(2, size=valset.shape[0]))
valset["result"].value_counts()

X_val = preprocess_pipeline.fit_transform(valset)
y_val = valset["result"]

In [82]:
forest_clf_pred = forest_clf.predict(X_val)

from sklearn.metrics import accuracy_score
accuracy_score(y_val, forest_clf_pred)

0.8449880350970487

 - 85% of prediction accuracy , the almosts bookmakers are about 60% with odds modulation

In [83]:
from sklearn.metrics import accuracy_score

rnd_pred = rnd_search.predict(X_val)

accuracy_score(y_val, rnd_pred)

0.8699813879287424

### Test with only Common Opponent

In [84]:
X_train = stats_pipeline.fit_transform(dataset)
y_train = dataset["result"]

In [85]:
X_test = stats_pipeline.fit_transform(test_set)
y_test = test_set["result"]

In [86]:
X_val = stats_pipeline.fit_transform(valset)
y_val = valset["result"]

In [87]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=100, high=500),
        'max_features': randint(low=5, high=15),
    }

forest_reg = RandomForestClassifier(random_state=42)
rnd_search_co = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=42, n_jobs=-1)
rnd_search_co.fit(X_train, y_train) 

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
          fit_params=None, iid='warn', n_iter=10, n_jobs=-1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x11f51fd68>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x11f51ff28>},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring='neg_mean_squared_error',
          verbose=0)

In [88]:
rnd_search_co.best_params_

{'max_features': 6, 'n_estimators': 443}

In [89]:
feature_importances = rnd_search_co.best_estimator_.feature_importances_
#sorted(zip(feature_importan)ces, list(dataset.columns.values)), reverse=True))
feature_importances[32:] ## useless

array([], dtype=float64)

In [90]:
from sklearn.metrics import accuracy_score

rnd_pred_co = rnd_search_co.predict(X_test)
accuracy_score(y_test, rnd_pred_co)

0.804

In [91]:
rnd_pred_co = rnd_search_co.predict(X_val)
accuracy_score(y_val, rnd_pred_co)

0.8529646370646105

In [92]:
save_model(rnd_search_co, "rnd_search_co")

## Prediction pre-match 11/10/18

In [93]:
import pickle

PATH = 'models/'

def load_model(name, path=PATH):
    file = open(path + name, 'rb')
    obj = pickle.load(file)
    file.close()
    return obj

model = load_model("rnd_search_co")

In [94]:
from sqlalchemy import create_engine
import psycopg2 as pg
import requests as req

URL = 'postgresql://dataset:dataset1747@35.204.62.91:5432/dataset-dump1'
engine = create_engine(URL)

def get_data_prediction(date, winner, looser):
    URL = "https://raw.githubusercontent.com/panaC/tennis-dataset/master/app/dataset/prediction.sql"
    with engine.connect() as conn, conn.begin():
        return pd.read_sql(req.get(URL).text.format(date=date, winner=winner, looser=looser), conn)

In [95]:
prediction_data = get_data_prediction('11/10/2018', 'Stefanos Tsitsipas', 'Alex de Minaur')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0           0.104167                 12             -36.375      -4.125   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0               0.0625             2.3125                        -12.5   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                          -0.5        -16.1875                    -2.3125   

           ...           return_rating_20years  \
0          ...                      -17.083333   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                              0.565476            -11.922619   

   return_games_played_20years  service_point_won_20years  \
0                         0.75                  -5.077381   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                      -0.5                -3.154762                     0.0   

   h2h  minutes_loser_winner  
0  1.0                  None  

[1 rows x 37 columns]

In [96]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [97]:
model.predict_proba(X_pred)

array([[0.0744921, 0.9255079]])

In [98]:
prediction_data["result"][0]

1

In [99]:
pred[0]

1

There is 97% of probability that Tsitsipas win because the result is 1 and 1 = first player in fct

In [100]:
prediction_data = get_data_prediction('11/10/2018', 'Kevin Anderson', 'Dominic Thiem')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0           0.067935                 13             -15.825       -5.65   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0                  1.6          -6.716667                        2.075   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      0.516667           5.975                  -0.333333   

           ...           return_rating_20years  \
0          ...                        9.790835   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                              3.092286              0.669302   

   return_games_played_20years  service_point_won_20years  \
0                     -0.72378                  -2.896813   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                  2.132079                -0.335131                     0.0   

   h2h  minutes_loser_winner  
0  1.0                  None  

[1 rows x 37 columns]

In [101]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [102]:
model.predict_proba(X_pred)

array([[0.09029345, 0.90970655]])

In [103]:
prediction_data["result"][0]

1

In [104]:
pred[0]

1

- warning combine option. I think that 1 year is too short for head2head , add 3 new colonne with may be 10 years combine

In [105]:
prediction_data = get_data_prediction('11/10/2018', 'Alexander Zverev', 'Marin Cilic')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0           0.091912                 15           14.346154    4.230769   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0            -1.076923          -2.961538                     3.153846   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      1.115385        3.538462                   1.538462   

           ...           return_rating_20years  \
0          ...                        3.321875   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                              0.985911             -0.114494   

   return_games_played_20years  service_point_won_20years  \
0                     0.206544                    3.67691   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                  0.968995                  2.11016                     1.0   

        h2h  minutes_loser_winner  
0  0.666667                  None  

[1 rows x 37 columns]

In [106]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [107]:
model.predict_proba(X_pred)

array([[0.81264108, 0.18735892]])

In [108]:
prediction_data["result"][0]

0

In [109]:
pred[0]

0

In [110]:
prediction_data = get_data_prediction('11/10/2018', 'Novak Djokovic', 'John Isner')
prediction_data

uncertainty_1year  count_match_1year  serve_rating_1year  aces_1year  \
0            0.15625                  8              39.625      20.625   

   double_faults_1year  first_serve_1year  first_serve_point_won_1year  \
0                  1.0              3.125                        9.375   

   second_serve_point_won_1year  bp_saved_1year  service_game_played_1year  \
0                      -11.6875         21.5625                     7.5625   

           ...           return_rating_20years  \
0          ...                      -68.709553   

   first_serve_return_point_won_20years  bp_converted_20years  \
0                            -13.003473            -14.844916   

   return_games_played_20years  service_point_won_20years  \
0                     2.604565                   3.238263   

   return_point_won_20years  total_point_won_20years  winner_loser_match_win  \
0                -14.168259                -5.131055                     2.0   

        h2h  minutes_loser_winner  
0  0.333333                  None  

[1 rows x 37 columns]

In [111]:
prediction_data.insert(prediction_data.shape[1], "result", np.random.randint(2, size=prediction_data.shape[0]))

X_pred = stats_pipeline.fit_transform(prediction_data)
pred = model.predict(X_pred)

In [112]:
model.predict_proba(X_pred)

array([[0.80586907, 0.19413093]])

In [113]:
prediction_data["result"][0]

0

In [114]:
pred[0]

0

if prediction_data["result"][0] == 0 then 
    
    pred = 1 = los or pred = 0 = winner 

else

    pred = 1 = win or pred = 0 = los